# Generated by Django 3.0.7 on 2021-07-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('true_false', '0002_auto_20210628_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tf_question',
            options={'ordering': ['grade'], 'verbose_name': 'Câu hỏi True/False', 'verbose_name_plural': 'Câu hỏi True/False'},
        ),
    ]
