# Generated by Django 3.0.7 on 2021-07-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210729_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Branch', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Department', verbose_name='Grade'),
        ),
    ]
