# Generated by Django 3.1 on 2021-06-28 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Đề thi', 'verbose_name_plural': 'Đề thi'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='random_order',
            field=models.BooleanField(default=False, help_text='Sắp xếp câu hỏi ngẫu nhiên', verbose_name='Câu hỏi ngẫu nhiên'),
        ),
    ]
