# Generated by Django 3.0.7 on 2021-07-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210729_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Grade', verbose_name='Bậc thợ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Branch', verbose_name='Chi nhánh'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='Nội dung câu hỏi', max_length=1000, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Giải thích đáp án (chỉ hiện thị khi thí sinh làm bài xong)', max_length=2000, verbose_name='Giải thích'),
        ),
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Hình vẽ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Grade', verbose_name='Bậc thợ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(blank=True, to='quiz.Quiz', verbose_name='Bộ đề'),
        ),
    ]
