# Generated by Django 3.0.7 on 2021-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210730_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(help_text='Đường dẫn tới bài thi', max_length=120, verbose_name='Đường dẫn'),
        ),
    ]
