# Generated by Django 3.1 on 2021-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210628_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Thời gian làm bài'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hạn cuối làm bài'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mở đề'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Tên bài thi'),
        ),
    ]
