# Generated by Django 3.0.7 on 2021-06-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210628_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='depart',
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Department', verbose_name='Phòng ban'),
        ),
    ]
