# Generated by Django 3.0.7 on 2021-06-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210628_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('0', 'Nam'), ('1', 'Nữ')], default='0', max_length=1, verbose_name='Giới tính'),
        ),
    ]
