# Generated by Django 3.0.7 on 2021-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210628_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian mở đề'),
        ),
    ]
