# Generated by Django 3.0.7 on 2021-07-29 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0012_auto_20210628_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=512, null=True, verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': 'Chi nhánh',
            },
        ),
        migrations.CreateModel(
            name='ProfileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_file', models.FileField(upload_to='profile_list')),
            ],
            options={
                'verbose_name': 'Tải lên danh sách thí sinh',
                'verbose_name_plural': 'Tải lên danh sách thí sinh',
            },
        ),
        migrations.AlterModelOptions(
            name='sitting',
            options={'permissions': (('view_sittings', 'Có thể xem toàn bộ bài thi.'),)},
        ),
        migrations.RemoveField(
            model_name='department',
            name='categories',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian mở đề'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Hoàn thành'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='current_score',
            field=models.IntegerField(verbose_name='Điểm hiện tại'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='incorrect_questions',
            field=models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Câu hỏi sai'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_list',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Danh sách câu hỏi'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='question_order',
            field=models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Thứ tự câu hỏi'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Thí sinh'),
        ),
        migrations.AlterField(
            model_name='sitting',
            name='user_answers',
            field=models.TextField(blank=True, default='{}', verbose_name='Câu trả lời của thí sinh'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Branch', verbose_name='Chi nhánh'),
        ),
    ]
