# Generated by Django 3.0.7 on 2021-07-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210729_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupload',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Branch', verbose_name='Chi nhánh'),
        ),
    ]
