# Generated by Django 3.0.7 on 2021-07-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay_question',
            options={'verbose_name': 'Câu hỏi tự luận', 'verbose_name_plural': 'Câu hỏi tự luận'},
        ),
    ]
