# Generated by Django 3.1 on 2021-06-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'verbose_name': 'Câu hỏi nhiều lựa chọn', 'verbose_name_plural': 'Câu hỏi nhiều lựa chọn'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(help_text='Câu trả lời', max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, help_text='Câu trả lời đúng', verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multichoice.mcquestion', verbose_name='Câu hỏi'),
        ),
    ]
