# Generated by Django 3.1 on 2021-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0002_auto_20210628_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='quiz_file',
            field=models.FileField(default=1, upload_to='sample_quiz'),
            preserve_default=False,
        ),
    ]
