# Generated by Django 3.0.7 on 2021-07-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210729_1949'),
        ('multichoice', '0002_auto_20210729_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Branch', verbose_name='Chi nhánh'),
        ),
        migrations.AddField(
            model_name='upload',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Grade', verbose_name='Bậc thợ'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='quiz_file',
            field=models.FileField(upload_to='quiz'),
        ),
    ]
