# Generated by Django 3.1 on 2021-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0003_upload_quiz_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
