# Generated by Django 3.0.7 on 2021-06-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20210628_2019'),
        ('multichoice', '0005_auto_20210628_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Câu trả lời', 'verbose_name_plural': 'Câu trả lời'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': 'Tải lên danh sách câu hỏi', 'verbose_name_plural': 'Tải lên danh sách câu hỏi'},
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Nội dung'), ('random', 'Ngẫu nhiên'), ('none', 'Không chọn')], help_text='The order in which multichoice answer options are displayed to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Phân loại'),
        ),
    ]
