# Generated by Django 3.0.7 on 2021-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0006_auto_20210628_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcquestion',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('content', 'Nội dung'), ('random', 'Ngẫu nhiên'), ('none', 'Không chọn')], help_text='The order in which multichoice answer options are displayed to the user', max_length=30, null=True, verbose_name='Thứ tự câu trả lời'),
        ),
    ]
